;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█░░░█▀█░█▀▄░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░░░█░█░█▀▄░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀│
;; │░Created░By░Aditya░Shakya░@adi1090x░░░░░░░░░░░░░░░░░░░░░░░░░│
;; └────────────────────────────────────────────────────────────┘

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

;; Use pywal.sh in scripts directory to use colors from an image/wallpaper.

;; main colors
background = #001A1F23
background-light = #343d45
foreground = #C4C7C5
sep = #2A3338
background-alt = #550C2F2C

white = #FFFFFF
black = #000000
red = #B88A8A
pink = #9A5C7D
purple = #7D7DB8
blue = #7A9CB8
cyan = #7AB8B8
teal = #7A9C9C
green = #7A9C7A
lime = #9CB87A
yellow = #B89C7A
amber = #B87A7A
orange = #B87A7A
brown = #9C7A7A
indigo = #7A7AB8
gray = #7A7A7A
blue-gray = #7A9CB8

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
